name: files
description: Ubuntu flutter community file manager.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  code_assets: ^0.19.7
  collection: ^1.16.0

  ffi: ^2.1.4
  filesize: ^2.0.1
  flutter:
    sdk: flutter

  handy_window: ^0.4.0
  hooks: ^0.20.1
  intl: ^0.20.2
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2

  material_design_icons_flutter: ^7.0.7296 
  mime: ^2.0.0

  pasteboard: ^0.4.0
  path: ^1.8.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1

  recase: ^4.1.0
  super_clipboard: ^0.9.1
  ubuntu_service: ^0.4.0+1
  udisks:
    git: https://github.com/HrX03/udisks.dart
  url_launcher: ^6.3.2
  windows_path_provider:
    git:
      url: https://github.com/HrX03/windows_path_provider.git
  xdg_directories: ^1.0.0
  yaru: ^8.3.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  isar_community_generator: ^3.3.0-dev.2
  lint: ^2.8.0

flutter:
  uses-material-design: true
